# Generated by Django 4.2 on 2025-02-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["date"],
                "verbose_name": "расписание",
                "verbose_name_plural": "расписания",
            },
        ),
    ]
