# Generated by Django 4.2 on 2025-02-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
        migrations.AlterModelOptions(
            name='grouplesson',
            options={'ordering': ['number'], 'verbose_name': 'пары'},
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='subgroup',
            field=models.CharField(blank=True, choices=[('all', 'Общая'), ('first_subgroup', '1п/г'), ('second_subgroup', '2п/г'), ('first_brigade', '1 бригада'), ('second_brigade', '2 бригада'), ('third_brigade', '3 бригада')], default='all', max_length=15, verbose_name='подгруппа'),
        ),
    ]
