# Generated by Django 4.2 on 2025-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_exercise_options_alter_grouplesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='classroom',
            field=models.CharField(blank=True, choices=[('211', 'cr-211'), ('212', 'cr-212'), ('108', 'cr-108')], default='---', max_length=15, verbose_name='кабинет'),
        ),
    ]
