# Generated by Django 4.2 on 2025-02-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_classroom_remove_grouplesson_exercise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouplesson",
            name="classroom",
            field=models.ForeignKey(
                default="---",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="classroom_lessons",
                to="schedule.classroom",
                verbose_name="кабинет",
            ),
        ),
    ]
