# Generated by Django 4.2 on 2025-02-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_alter_grouplesson_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouplesson",
            name="classroom",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classroom_lessons",
                to="schedule.classroom",
                verbose_name="кабинет",
            ),
        ),
    ]
