# Generated by Django 4.2 on 2025-02-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_alter_grouplesson_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouplesson",
            name="classroom",
        ),
    ]
