# Generated by Django 4.2 on 2025-02-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_grouplesson_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouplesson",
            name="number",
            field=models.CharField(
                choices=[
                    ("l1", "1"),
                    ("l2", "2"),
                    ("l3", "3"),
                    ("l4", "4"),
                    ("l5", "5"),
                    ("l6", "6"),
                    ("l7", "7"),
                ],
                max_length=2,
                verbose_name="номер пары",
            ),
        ),
    ]
