# Generated by Django 4.2 on 2025-03-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_grouplesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_set', to='schedule.schedule', verbose_name='расписание'),
        ),
    ]
