# Generated by Django 4.2 on 2025-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='number',
            field=models.CharField(choices=[('n1', '1'), ('n2', '2'), ('n3', '3'), ('n4', '4'), ('n5', '5'), ('n6', '6'), ('n7', '7')], max_length=2, verbose_name='номер пары'),
        ),
    ]
