# Generated by Django 4.2 on 2025-05-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0016_alter_grouplesson_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grouplesson",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="grouplesson",
            name="classroom",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classroom",
                to="schedule.classroom",
                verbose_name="кабинет",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouplesson",
            unique_together={("schedule", "number", "subgroup", "classroom")},
        ),
    ]
