# Generated by Django 4.2 on 2025-02-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="major",
            options={
                "verbose_name": "специальность",
                "verbose_name_plural": "специальности",
            },
        ),
    ]
