# Generated by Django 4.2 on 2025-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0002_alter_major_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="название специальности"
            ),
        ),
    ]
