# Generated by Django 4.2 on 2025-01-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "группа", "verbose_name_plural": "группы"},
        ),
    ]
