# Generated by Django 4.2 on 2025-02-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_subgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgroup',
            options={'verbose_name': 'подгруппа', 'verbose_name_plural': 'подгруппы'},
        ),
    ]
