# Generated by Django 4.2 on 2025-02-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_exercise_options_alter_grouplesson_options_and_more'),
        ('group', '0004_alter_subgroup_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubGroup',
        ),
    ]
