# Generated by Django 4.2 on 2025-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0005_delete_subgroup"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=5, unique=True, verbose_name="Название группы"
            ),
        ),
        migrations.RemoveField(
            model_name="group",
            name="course",
        ),
    ]
