# Generated by Django 4.2 on 2025-06-29 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="grade_language",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        3, "Оценка должна быть не менее 3"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Оценка должна быть не более 5"
                    ),
                ],
                verbose_name="Оценка по иностранному языку",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="grade_math",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        3, "Оценка должна быть не менее 3"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Оценка должна быть не более 5"
                    ),
                ],
                verbose_name="Оценка по математике",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="grade_physics",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        3, "Оценка должна быть не менее 3"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Оценка должна быть не более 5"
                    ),
                ],
                verbose_name="Оценка по физике",
            ),
        ),
    ]
