# Generated by Django 4.2 on 2025-06-27 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="average_grade",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_job",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_passport_issued_by",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_passport_issued_date",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_passport_number",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_passport_series",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="father_phone",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="grade_biology",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="grade_chemistry",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="grade_language",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="grade_math",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="grade_physics",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="grade_russian",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_job",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_name",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_passport_issued_by",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_passport_issued_date",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_passport_number",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_passport_series",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="mother_phone",
        ),
        migrations.AddField(
            model_name="applicant",
            name="education_base",
            field=models.CharField(
                blank=True,
                choices=[("9", "На базе 9 классов"), ("11", "На базе 11 классов")],
                max_length=2,
                verbose_name="База образования",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="registration_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="Регистрационный номер",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_job",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Место работы и должность представителя 1",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="ФИО представителя 1 (мама/жена)",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_passport_issued_by",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Кем выдан паспорт представителя 1",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_passport_issued_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата выдачи паспорта представителя 1",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_passport_number",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="Номер паспорта представителя 1"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_passport_series",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Серия паспорта представителя 1"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative1_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Телефон представителя 1"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_job",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Место работы и должность представителя 2",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="ФИО представителя 2 (папа/муж)",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_passport_issued_by",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Кем выдан паспорт представителя 2",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_passport_issued_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата выдачи паспорта представителя 2",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_passport_number",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="Номер паспорта представителя 2"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_passport_series",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Серия паспорта представителя 2"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="representative2_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Телефон представителя 2"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="address",
            field=models.TextField(
                blank=True, verbose_name="Адрес места жительства по паспорту"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="address_actual",
            field=models.TextField(
                blank=True, verbose_name="Фактический адрес места жительства"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("бюджет", "Финансируемые из средств бюджета Республики Татарстан"),
                    ("коммерция", "На места с полным возмещением затрат"),
                ],
                max_length=50,
                verbose_name="Бюджет/коммерция",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Место рождения"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="certificate_issued_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выдачи аттестата"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="certificate_series",
            field=models.CharField(
                blank=True, max_length=14, verbose_name="Номер аттестата"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="citizenship",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Гражданство"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="graduation_institution",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Наименование учебного заведения",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1980, "Год должен быть не ранее 1980"
                    ),
                    django.core.validators.MaxValueValidator(
                        2025, "Год не может быть в будущем"
                    ),
                ],
                verbose_name="Год окончания учебного заведения",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="inn",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="medical_policy",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Медицинский полис"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="military_id",
            field=models.BooleanField(
                default=False, verbose_name="Приписное свидетельство (для юношей)"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Национальность"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="needs_dormitory",
            field=models.BooleanField(
                default=False, verbose_name="Нуждается в общежитии"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_division_code",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="Код подразделения"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_issued_by",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Кем выдан"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_issued_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="Номер паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_registration_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата регистрации прописки по паспорту",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_series",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Серия паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="snils",
            field=models.CharField(blank=True, max_length=11, verbose_name="СНИЛС"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pharmacy", "Фармация"),
                    ("nursing", "Сестринское дело"),
                    ("midwifery", "Акушерское дело"),
                    ("lab_diagnostics", "Лабораторная диагностика"),
                    ("medical_treatment", "Лечебное дело"),
                ],
                max_length=50,
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="student_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email абитуриента"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="student_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Телефонказа абитуриента"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="study_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("очная", "Очная форма обучения"),
                    ("очно-заочная", "Очно-заочная (вечерняя) форма обучения"),
                ],
                max_length=20,
                verbose_name="Форма обучения",
            ),
        ),
        migrations.CreateModel(
            name="ApplicantSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=100, verbose_name="Название предмета"),
                ),
                (
                    "grade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                3, "Оценка должна быть не менее 3"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "Оценка должна быть не более 5"
                            ),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="applicant.applicant",
                    ),
                ),
            ],
            options={
                "unique_together": {("applicant", "subject_name")},
            },
        ),
    ]
