# Generated by Django 4.2 on 2025-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="documents_submitted",
            field=models.CharField(
                blank=True,
                choices=[("оригинал", "Оригинал"), ("копия", "Копия")],
                max_length=10,
                null=True,
                verbose_name="Тип поданных документов",
            ),
        ),
    ]
