# Generated by Django 4.2 on 2025-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="education_base",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("бюджет", "Финансируемые из средств бюджета Республики Татарстан"),
                    ("коммерция", "На места с полным возмещением затрат"),
                ],
                max_length=50,
                verbose_name="Бюджет/коммерция",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("pharmacy", "Фармация"),
                    ("nursing", "Сестринское дело"),
                    ("nursing_zaochno", "Сестринское дело очно-заочно"),
                    ("midwifery", "Акушерское дело"),
                    ("lab_diagnostics", "Лабораторная диагностика"),
                    ("medical_treatment", "Лечебное дело"),
                    ("medical_treatment_11", "Лечебное дело на базе 11 класса"),
                ],
                max_length=50,
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="study_form",
            field=models.CharField(
                choices=[
                    ("очная", "Очная форма обучения"),
                    ("очно-заочная", "Очно-заочная (вечерняя) форма обучения"),
                ],
                max_length=20,
                verbose_name="Форма обучения",
            ),
        ),
    ]
