# Generated by Django 4.2 on 2025-07-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0002_remove_applicant_education_base_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="gosuslugi",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Подал через госуслуги РФ"
            ),
        ),
    ]
