# Generated by Django 4.2 on 2025-06-27 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0002_remove_applicant_average_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="grade_biology",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        3, "Оценка должна быть не менее 3"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Оценка должна быть не более 5"
                    ),
                ],
                verbose_name="Оценка по биологии",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="grade_chemistry",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        3, "Оценка должна быть не менее 3"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Оценка должна быть не более 5"
                    ),
                ],
                verbose_name="Оценка по химии",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="grade_russian",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        3, "Оценка должна быть не менее 3"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Оценка должна быть не более 5"
                    ),
                ],
                verbose_name="Оценка по русскому языку",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("бюджет", "Финансируемые из средств бюджета Республики Татарстан"),
                    ("коммерция", "На места с полным возмещением затрат"),
                ],
                max_length=50,
                verbose_name="Бюджет/коммерция",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="education_base",
            field=models.CharField(
                choices=[("9", "На базе 9 классов"), ("11", "На базе 11 классов")],
                max_length=2,
                verbose_name="База образования",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("pharmacy", "Фармация"),
                    ("nursing", "Сестринское дело"),
                    ("midwifery", "Акушерское дело"),
                    ("lab_diagnostics", "Лабораторная диагностика"),
                    ("medical_treatment", "Лечебное дело"),
                ],
                max_length=50,
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="student_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Телефон абитуриента"
            ),
        ),
        migrations.DeleteModel(
            name="ApplicantSubject",
        ),
    ]
