# Generated by Django 4.2 on 2025-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0003_applicant_gosuslugi"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="documents_canceled",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Забрал документы"
            ),
        ),
    ]
