# Generated by Django 4.2 on 2025-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0004_applicant_documents_canceled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="registration_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Регистрационный номер",
            ),
        ),
    ]
