# Generated by Django 4.2 on 2025-01-28 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите заголовок статьи",
                        max_length=255,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="введите текст статьи",
                        verbose_name="содержание статьи",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="дата изменения"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        help_text="выберите автора стать",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        related_query_name="user_news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "новости",
            },
        ),
    ]
