# Generated by Django 4.2 on 2025-02-01 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publisher",
            field=models.ForeignKey(
                help_text="выберите автора статьи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                related_query_name="user_news",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
    ]
