# Generated by Django 4.2 on 2025-01-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Administrator"),
                ],
                default="student",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=5, verbose_name="Название группы"),
                ),
                (
                    "course",
                    models.IntegerField(
                        choices=[
                            (1, "1 курс"),
                            (2, "2 курс"),
                            (3, "3 курс"),
                            (4, "4 курс"),
                        ],
                        verbose_name="Номер курса",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "course")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_students",
                to="users.group",
            ),
        ),
    ]
