# Generated by Django 4.2 on 2025-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Студент"),
                    ("teacher", "Преподаватель"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
