# Generated by Django 4.2 on 2025-01-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_alter_group_options"),
        ("users", "0006_alter_user_options_alter_user_group_delete_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_students",
                to="group.group",
                verbose_name="группа",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Студент"),
                    ("teacher", "Преподаватель"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=10,
                verbose_name="роль",
            ),
        ),
    ]
