# Generated by Django 4.2 on 2025-02-14 15:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="father_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="отчество",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None, verbose_name="номер телефона"
            ),
        ),
    ]
