# Generated by Django 4.2 on 2025-02-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_father_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
    ]
