# Generated by Django 4.2 on 2025-02-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0002_alter_major_options"),
        ("users", "0011_remove_user_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjects", models.TextField(verbose_name="преподаваемые дисциплины")),
                (
                    "education_level",
                    models.TextField(verbose_name="уровень образования"),
                ),
                ("qualification", models.TextField(verbose_name="квалификация")),
                (
                    "total_experience",
                    models.PositiveIntegerField(verbose_name="общий стаж работы (лет)"),
                ),
                (
                    "teaching_experience",
                    models.PositiveIntegerField(
                        verbose_name="педагогический стаж (лет)"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="major.major",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
